name: CI

# Only trigger CI for pushes to main / develop
on:
  push:
    branches: 
      - main
      - develop
env:
  # Setup a temporary environment variable to format the artifact name
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  # Format a unique artifact name for every CI run
  format-artifact-name:
    runs-on: self-hosted
    outputs:
      # Define the output variable for this job
      formatted-artifact-name: ${{ steps.generate-artifact-name.outputs.ARTIFACT_NAME }}
    steps:
      # Replace / with _ for branch name
      - name: Format BRANCH_NAME
        env:
          name: "${{env.BRANCH_NAME}}"
        run: |
          echo "FORMATTED_BRANCH_NAME=${name/\//_}" >> $GITHUB_ENV
      # Get the first 7 chars from commit sha
      - name: Short SHA
        run: |
          export SHORT_SHA=$(echo '${{ github.sha }}' | cut -c1-7)
          echo "SHA_SHORT=$SHORT_SHA" >> $GITHUB_ENV
      # Get current time
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: MMDDHHmm
          utcOffset: "+08:00"
      # Format and output the final ARTIFACT_NAME
      - name: Set Artifact Name
        id: generate-artifact-name
        run: echo "ARTIFACT_NAME=storybook_${{env.FORMATTED_BRANCH_NAME}}_${{steps.current-time.outputs.formattedTime}}_${{env.SHA_SHORT}}"  >> $GITHUB_OUTPUT
  build:
    runs-on: self-hosted
    # Defines the dependency for this job
    needs: [format-artifact-name]
    steps:
      # Checkout the repo to current commit
      - uses: actions/checkout@v3
      - name: Output Metadata
        run: echo ${{ needs.format-artifact-name.outputs.formatted-artifact-name }} > 'filename'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ needs.format-artifact-name.outputs.formatted-artifact-name }}
          path: .
      - name: Upload Filename
        uses: actions/upload-artifact@v3.1.2
        with:
          name: filename
          path: filename
